Refactor self-hosted deploy workflow: Add error handling for database update failure

diff --git a/.github/actions/self-hosted-run/common/update-base/action.yml b/.github/actions/self-hosted-run/common/update-base/action.yml
--- a/.github/actions/self-hosted-run/common/update-base/action.yml
+++ b/.github/actions/self-hosted-run/common/update-base/action.yml
@@ -35,11 +35,16 @@ runs:
         echo -e "\033[34m=== Starting database update ===\033[0m"
         venv_flag=$([ "$USE_VENV" == "true" ] && echo "--use-venv" || echo "")
         sudo -u $SERVER_USER $PYTHON_SCRIPT --databases "$DB_LIST" --main_path "$MAIN_PATH" --config "$ODOO_CONFIG" --user "$SERVER_USER" --hard $venv_flag
+        update_status=$?
 
         sudo systemctl start $ODOO_SERVICE && sleep 10
         echo -e "\033[34m=== SHOW STATUS ODOO ===\033[0m"
         sudo systemctl status $ODOO_SERVICE
         echo "::endgroup::"
+        if [ $update_status -ne 0 ]; then
+          echo -e "\033[31mError: Database update failed.\033[0m"
+          exit 1
+        fi
       env:
         ODOO_SERVICE: ${{ inputs.ODOO_SERVICE }}
         USE_VENV: ${{ inputs.USE_VENV }}
diff --git a/.github/actions/self-hosted-run/common/update-changed/action.yml b/.github/actions/self-hosted-run/common/update-changed/action.yml
--- a/.github/actions/self-hosted-run/common/update-changed/action.yml
+++ b/.github/actions/self-hosted-run/common/update-changed/action.yml
@@ -32,7 +32,12 @@ runs:
         sudo systemctl restart $ODOO_SERVICE && sleep 10
         venv_flag=$([ "$USE_VENV" == "true" ] && echo "--use-venv" || echo "")
         sudo -u $SERVER_USER $PYTHON_SCRIPT --databases "$DB_LIST" --main_path "$MAIN_PATH" --config "$ODOO_CONFIG" --user "$SERVER_USER" $venv_flag
+        update_status=$?
         echo "::endgroup::"
+        if [ $update_status -ne 0 ]; then
+          echo -e "\033[31mError: Database update failed.\033[0m"
+          exit 1
+        fi
       env:
         ODOO_SERVICE: ${{ inputs.ODOO_SERVICE }}
         USE_VENV: ${{ inputs.USE_VENV }}
