Remove conditional check for failure when starting Odoo service in action.yml

diff --git a/.github/actions/self-hosted-run/common/update-changed/action.yml b/.github/actions/self-hosted-run/common/update-changed/action.yml
--- a/.github/actions/self-hosted-run/common/update-changed/action.yml
+++ b/.github/actions/self-hosted-run/common/update-changed/action.yml
@@ -86,7 +86,8 @@ runs:
       shell: bash
 
     - name: Start Odoo
-      if: ${{ inputs.exclusive_update == 'true' || failure()}}
+      # if: ${{ inputs.exclusive_update == 'true' || failure()}}
+      if: ${{ inputs.exclusive_update == 'true' }}
       run: |
         echo "DEBUG ====> Restarting Odoo Service"
         sudo systemctl restart $ODOO_SERVICE
